version: '3.7'
services:
  web:
    image: invasi0m/bun:alpine
    container_name: bun-alpine
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 8080:8080
      - 4321:4312
    volumes:
      - ./app:/app
    healthcheck:
      test: ["CMD-SHELL", "bun -v"]
      interval: 2s
      timeout: 5s
      retries: 5