version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: doobie-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql # root user = root
      - MYSQL_DATABASE=world
    ports:
      - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./sql:/raw/data
