version: '3.7'
services:
  db:
    image: postgres:15.2-alpine
    container_name: world-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=world
    ports:
      - '5432:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data
      - ./sql:/raw/data
