#!/bin/bash
  if [[ $1 = "up" ]] || [[ $1 = "start" ]]; then
     docker compose -f ${PWD}/postgres/docker-compose.yml up -d
     docker compose -f ${PWD}/mysql/docker-compose.yml up -d
  elif [[ $1 = "down" ]] || [[ $1 = "stop" ]] || [[ $1 = "kill" ]]; then
     docker rm -f $(docker ps -a | grep doobie | awk '$1 {print $1}')
  else
    echo "Choose one of the following options:"
    echo "Start services (instance up | instance start)"
    echo "Stop services (instance down | instance stop | instance kill)"
fi
